apiVersion: apps/v1
kind: Deployment
metadata:
  name: entitymanager-deployment-test
  namespace: ingress-nginx
  labels:
    app: entitymanager123
spec:
  replicas: 2
  selector:
    matchLabels:
      app: entitymanager123
  template:
    metadata:
      labels:
        app: entitymanager123
    spec:
      containers:
      - name: entitymanager123
        image: cpdevelop.azurecr.io/entitymanager:13
        ports:
        - containerPort: 8083
